export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const HEADING_NEXT_WORK_HISTORY = "HEADING => NEXT_WORK => HISTORY";
export const WORK_HISTORY_NEXT_THEORETICAL =
  "WORK_HISTORY => NEXT => THEORETICAL";
export const THEORETICAL_NEXT_ABILITIES = "THEORETICAL => NEXT => ABILITIES";
export const ABILITIES_NEXT_RECOGNITION = "ABILITIES => NEXT => RECOGNITION";
export const RECOGNITION_NEXT_SOFT_SKILL = "RECOGNITION => NEXT => PERSONALITY";
export const SOFT_SKILL_NEXT_SUMMARY = "PERSONALITY => NEXT => SUMMARY";
export const SUMMARY_NEXT_FINALIZE = "SUMMARY => NEXT => FINALIZE";
